spring.datasource.url=jdbc:postgresql://dpg-d867i7vavr4c73dh82mg-a.ohio-postgres.render.com/consignataria
spring.datasource.username=consignataria_user
spring.datasource.password=KpVUdgKSURfgMGJ0fv7PYJt6WyyZGebR
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect